# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/blog',
                'doc_host': 'https://barz-christian.github.io',
                'git_url': 'https://github.com/barz-christian/blog',
                'lib_path': 'blog'},
  'syms': {}}
