name: test
on:  [workflow_dispatch, pull_request, push]

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: setup solver
        run : |
          sudo apt-get install -y libopenmpi-dev glpk-utils 
          sudo apt-get install gcc g++ gfortran git cmake liblapack-dev pkg-config --install-recommends
          sudo apt-get install coinor-libipopt-dev
      - uses: fastai/workflows/nbdev-ci@master
      - uses: fastai/workflows/quarto-ghp@master
